# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  vmImage: 'ubuntu-22.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  displayName: 'npm install'

- script: node-sass Tailspin.SpaceGame.Web/wwwroot
  displayName: 'node-sass'

- task: gulp@1
  displayName: 'gulp'

- script: echo $(build.buildNumber) > Tailspin.SpaceGame.Web/wwwroot/buildinfo.txt

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build debug'
  inputs:
    command: 'build'
    arguments: '--configuration Debug'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish debug'
  inputs:
    command: 'publish'
    arguments: '--no-build --configuration Debug --output /tmp/Debug'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build release'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish release'
  inputs:
    command: 'publish'
    arguments: '--no-build --configuration Debug --output /tmp/Release'
